# Generated by Django 5.1.4 on 2025-01-01 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('telefono', models.CharField(max_length=20)),
                ('dni', models.CharField(max_length=20)),
                ('tipo_entrada', models.CharField(choices=[('GENERAL', 'General'), ('GOLDEN_NUM', 'Golden Numerada'), ('VIP', 'VIP'), ('VIP_NUM', 'VIP Numerada')], max_length=20)),
                ('numero_asiento', models.IntegerField(blank=True, null=True)),
                ('comprobante_pago', models.ImageField(upload_to='comprobantes/')),
                ('fecha_compra', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('VERIFICADO', 'Verificado'), ('RECHAZADO', 'Rechazado')], default='PENDIENTE', max_length=20)),
                ('codigo_qr', models.ImageField(blank=True, null=True, upload_to='qr/')),
            ],
            options={
                'unique_together': {('tipo_entrada', 'numero_asiento')},
            },
        ),
    ]
